var objects = [
    {
        "ObjectId": 244100,
        "UniqueId": "A2A64615-1184-41D0-92AD-308CBC34991C",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 2,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Banterij",
        "Number": "20",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1046 AN",
        "Longitude": 4.774738,
        "Latitude": 52.389736,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/A2/A6/46/15/A2A64615-1184-41D0-92AD-308CBC34991C/thumb/1.jpg",
        "Price": 269000,
        "PricePerYear": 20000,
        "Metrage": 207,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mevrouw",
            "GUID": "64A048A966B146BA9CE66430D3D66193",
            "Name": "Blaauwhof Makelaars (Amsterdam)",
            "Address": "Dukdalfweg 60",
            "City": "Amsterdam",
            "Postcode": "1041 BE",
            "ContactPersonName": "BOG Invoerder",
            "ContactEmailAddress": "makelaars@blaauwhof.nl",
            "PersonId": 14333,
            "Phonenumber": "020-4203200",
            "Logo": "blaauwhof.jpg",
            "CanonicalName": "Blaauwhof-Makelaars-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Banterij  20",
        "BuildingAddressInfo": "Banterij  20",
        "FullAddressInfo": "Banterij  20, 1046 AN, Amsterdam",
        "InsertedDateTime": "2016-06-08T16:30:01",
        "PrimaryUsage": "Bedrijfsruimte",
        "SaleOrRent": "",
        "PriceInfo": "#Koopprijs# &euro; 269.000, #HuurprijsPerJaar# &euro; 20.000, #HuurprijsPerMaand# &euro; 1.666",
        "MetrageInfo": "207 m&sup2;",
        "DetailLinkUrl": "A2A64615-1184-41D0-92AD-308CBC34991C/Amsterdam/Banterij/20",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 244019,
        "UniqueId": "01c0f1b3-8739-4379-9379-05af2259cad4",
        "AvailabilityCustom": "31-12-2016",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Museumplein",
        "Number": "5",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1071 DJ",
        "Longitude": 4.883426,
        "Latitude": 52.357555,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/01/c0/f1/b3/01c0f1b3-8739-4379-9379-05af2259cad4/thumb/1.jpg",
        "Price": null,
        "PricePerYear": 100000,
        "Metrage": 218,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 3,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Eveline Davidis",
            "ContactEmailAddress": "eveline.davidis@cbre.com",
            "PersonId": 17708,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Museumplein  5",
        "BuildingAddressInfo": "Museumplein  5",
        "FullAddressInfo": "Museumplein  5, 1071 DJ, Amsterdam",
        "InsertedDateTime": "2016-06-03T13:36:25",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#HuurprijsPerJaar# &euro; 100.000, #HuurprijsPerMaand# &euro; 8.333",
        "MetrageInfo": "218 m&sup2;",
        "DetailLinkUrl": "01c0f1b3-8739-4379-9379-05af2259cad4/Amsterdam/Museumplein/5",
        "Availability": "31-12-2016"
    },
    {
        "ObjectId": 243993,
        "UniqueId": "6dd097c3-8478-4510-a19e-529b28b8719d",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Herengracht",
        "Number": "477",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1017 BS",
        "Longitude": 4.890172,
        "Latitude": 52.365997,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/6d/d0/97/c3/6dd097c3-8478-4510-a19e-529b28b8719d/thumb/1.jpg",
        "Price": null,
        "PricePerYear": 72000,
        "Metrage": 200,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Eveline Davidis",
            "ContactEmailAddress": "eveline.davidis@cbre.com",
            "PersonId": 17708,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": "/media/objects/6d/d0/97/c3/6dd097c3-8478-4510-a19e-529b28b8719d/docs/PI NL Herengracht 477, Amsterdam Centrum.pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Herengracht  477",
        "BuildingAddressInfo": "Herengracht  477",
        "FullAddressInfo": "Herengracht  477, 1017 BS, Amsterdam",
        "InsertedDateTime": "2016-06-02T13:07:01",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#HuurprijsPerJaar# &euro; 72.000, #HuurprijsPerMaand# &euro; 6.000",
        "MetrageInfo": "200 m&sup2;",
        "DetailLinkUrl": "6dd097c3-8478-4510-a19e-529b28b8719d/Amsterdam/Herengracht/477",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 235559,
        "UniqueId": "498cbffd-c2a3-4797-9bcc-da9a07a8365a",
        "AvailabilityCustom": "01-06-2016",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Vondelstraat",
        "Number": "13",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1054 GC",
        "Longitude": 4.8782907,
        "Latitude": 52.36247,
        "ObjectTypeId": null,
        "PriceAverage": 275,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/49/8c/bf/fd/498cbffd-c2a3-4797-9bcc-da9a07a8365a/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 400,
        "MetrageStart": null,
        "SalesHeaderLine": "Vondelstraat 13",
        "AvailabilityId": 3,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Maarten van Dooren",
            "ContactEmailAddress": "maarten.vandooren@cbre.com",
            "PersonId": 6164,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Vondelstraat  13",
        "BuildingAddressInfo": "Vondelstraat  13",
        "FullAddressInfo": "Vondelstraat  13, 1054 GC, Amsterdam",
        "InsertedDateTime": "2016-03-01T14:04:54",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 275 m<sup>2<\/sup>/jr",
        "MetrageInfo": "400 m&sup2;",
        "DetailLinkUrl": "498cbffd-c2a3-4797-9bcc-da9a07a8365a/Amsterdam/Vondelstraat/13",
        "Availability": "01-06-2016"
    },
    {
        "ObjectId": 235288,
        "UniqueId": "627070d5-1afb-4773-aabf-4c55a1e9ce8b",
        "AvailabilityCustom": "",
        "ObjectName": "UN Studio",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Gustav Mahlerlaan",
        "Number": "350",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1082 ME",
        "Longitude": 4.8693576,
        "Latitude": 52.336872,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/62/70/70/d5/627070d5-1afb-4773-aabf-4c55a1e9ce8b/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 7049,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": null,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "CBRE",
            "ContactEmailAddress": "jantien.uitdebosch@cbre.com",
            "PersonId": 7072,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Gustav Mahlerlaan  350",
        "BuildingAddressInfo": "UN Studio, Gustav Mahlerlaan  350",
        "FullAddressInfo": "UN Studio, Gustav Mahlerlaan  350, 1082 ME, Amsterdam",
        "InsertedDateTime": "2016-02-15T14:57:57",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "7.049 m&sup2;",
        "DetailLinkUrl": "627070d5-1afb-4773-aabf-4c55a1e9ce8b/Amsterdam/Gustav-Mahlerlaan/350",
        "Availability": ""
    },
    {
        "ObjectId": 234138,
        "UniqueId": "ee842e79-9d6c-4a87-9cd1-159008509859",
        "AvailabilityCustom": "",
        "ObjectName": "Byzantium",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Stadhouderskade",
        "Number": "13",
        "NumberRangeTo": "14",
        "NumberSuffix": null,
        "Postcode": "1054 ES",
        "Longitude": 4.8805714,
        "Latitude": 52.362247,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/ee/84/2e/79/ee842e79-9d6c-4a87-9cd1-159008509859/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 1158,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Laura Hovestad en Maarten van Dooren",
            "ContactEmailAddress": "laura.hovestad@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Stadhouderskade  13-14",
        "BuildingAddressInfo": "Byzantium, Stadhouderskade  13-14",
        "FullAddressInfo": "Byzantium, Stadhouderskade  13-14, 1054 ES, Amsterdam",
        "InsertedDateTime": "2016-01-22T09:54:26",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "1.158 m&sup2;",
        "DetailLinkUrl": "ee842e79-9d6c-4a87-9cd1-159008509859/Amsterdam/Stadhouderskade/13-14",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 233826,
        "UniqueId": "0815d1b2-8038-4aa8-b13e-2d1920ee5f76",
        "AvailabilityCustom": "",
        "ObjectName": "Jupiter Plaza ArenA",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Herikerbergweg",
        "Number": "74",
        "NumberRangeTo": "108",
        "NumberSuffix": null,
        "Postcode": "1101 CM",
        "Longitude": 4.942975,
        "Latitude": 52.30851,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/08/15/d1/b2/0815d1b2-8038-4aa8-b13e-2d1920ee5f76/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 3587,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": null,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Merel van Oudvorst",
            "ContactEmailAddress": "merel.vanoudvorst@cbre.com",
            "PersonId": null,
            "Phonenumber": "20-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Herikerbergweg  74-108",
        "BuildingAddressInfo": "Jupiter Plaza ArenA, Herikerbergweg  74-108",
        "FullAddressInfo": "Jupiter Plaza ArenA, Herikerbergweg  74-108, 1101 CM, Amsterdam",
        "InsertedDateTime": "2016-01-14T10:50:58",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "3.587 m&sup2;",
        "DetailLinkUrl": "0815d1b2-8038-4aa8-b13e-2d1920ee5f76/Amsterdam/Herikerbergweg/74-108",
        "Availability": ""
    },
    {
        "ObjectId": 200906,
        "UniqueId": "2c0b3ab4-5a37-455b-9728-3c4e39747fec",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Johannes Vermeerstraat",
        "Number": "29",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1071 DL",
        "Longitude": 4.8842864,
        "Latitude": 52.356987,
        "ObjectTypeId": null,
        "PriceAverage": 395,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/2c/0b/3a/b4/2c0b3ab4-5a37-455b-9728-3c4e39747fec/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 504,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Laura Hovestad",
            "ContactEmailAddress": "laura.hovestad@cbre.com",
            "PersonId": null,
            "Phonenumber": "20-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Johannes Vermeerstraat  29",
        "BuildingAddressInfo": "Johannes Vermeerstraat  29",
        "FullAddressInfo": "Johannes Vermeerstraat  29, 1071 DL, Amsterdam",
        "InsertedDateTime": "2015-11-23T10:13:35",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 395 m<sup>2<\/sup>/jr",
        "MetrageInfo": "504 m&sup2;",
        "DetailLinkUrl": "2c0b3ab4-5a37-455b-9728-3c4e39747fec/Amsterdam/Johannes-Vermeerstraat/29",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 200796,
        "UniqueId": "469870d7-4124-4907-bccd-8abafd1278ac",
        "AvailabilityCustom": "",
        "ObjectName": "Egelenburg",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Egelenburg",
        "Number": "150",
        "NumberRangeTo": "152",
        "NumberSuffix": null,
        "Postcode": "1081 GK",
        "Longitude": 4.8636456,
        "Latitude": 52.32852,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/46/98/70/d7/469870d7-4124-4907-bccd-8abafd1278ac/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 239,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Laura Hovestad",
            "ContactEmailAddress": "laura.hovestad@cbre.com",
            "PersonId": null,
            "Phonenumber": "20-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": "/media/objects/46/98/70/d7/469870d7-4124-4907-bccd-8abafd1278ac/docs/PI-NED-Egelenburg-150-152-Amsterdam.pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Egelenburg  150-152",
        "BuildingAddressInfo": "Egelenburg, Egelenburg  150-152",
        "FullAddressInfo": "Egelenburg, Egelenburg  150-152, 1081 GK, Amsterdam",
        "InsertedDateTime": "2015-11-17T14:13:56",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "239 m&sup2;",
        "DetailLinkUrl": "469870d7-4124-4907-bccd-8abafd1278ac/Amsterdam/Egelenburg/150-152",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 200666,
        "UniqueId": "b84cb655-b9ee-41a1-b5c0-7f75aea5bc95",
        "AvailabilityCustom": "",
        "ObjectName": "Viñoly",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Aaron Coplandstraat",
        "Number": "8",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1082 MG",
        "Longitude": 4.8713493,
        "Latitude": 52.337185,
        "ObjectTypeId": null,
        "PriceAverage": 350,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/b8/4c/b6/55/b84cb655-b9ee-41a1-b5c0-7f75aea5bc95/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 2362,
        "MetrageStart": 1027,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Niels Hanssen",
            "ContactEmailAddress": "niels.hanssen@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Aaron Coplandstraat  8",
        "BuildingAddressInfo": "Viñoly, Aaron Coplandstraat  8",
        "FullAddressInfo": "Viñoly, Aaron Coplandstraat  8, 1082 MG, Amsterdam",
        "InsertedDateTime": "2015-11-16T12:29:36",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 350 m<sup>2<\/sup>/jr",
        "MetrageInfo": "2.362 m&sup2; #Vanaf# 1.027m&sup2;",
        "DetailLinkUrl": "b84cb655-b9ee-41a1-b5c0-7f75aea5bc95/Amsterdam/Aaron-Coplandstraat/8",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 200559,
        "UniqueId": "2e8b18cb-8a0c-40c9-ab36-702a6a44ea36",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 2,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Snijdersbergweg",
        "Number": "95",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1105 AN",
        "Longitude": 4.944705,
        "Latitude": 52.298504,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/2e/8b/18/cb/2e8b18cb-8a0c-40c9-ab36-702a6a44ea36/thumb/1.jpg",
        "Price": null,
        "PricePerYear": 212260,
        "Metrage": 2361,
        "MetrageStart": 2361,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "2E9188758DE84DF5BB7028F429EC364F",
            "Name": "Van Lonkhuizen Makelaars (Weesp)",
            "Address": "Postbus 342",
            "City": "Weesp",
            "Postcode": "1380 AH",
            "ContactPersonName": "Maurits Kuppens",
            "ContactEmailAddress": "info@vanlonkhuizen.nl",
            "PersonId": null,
            "Phonenumber": "294-480355",
            "Logo": "lonkhuizen.JPG",
            "CanonicalName": "Van-Lonkhuizen-Makelaars-(Weesp)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Snijdersbergweg  95",
        "BuildingAddressInfo": "Snijdersbergweg  95",
        "FullAddressInfo": "Snijdersbergweg  95, 1105 AN, Amsterdam",
        "InsertedDateTime": "2015-11-05T15:26:03",
        "PrimaryUsage": "Bedrijfsruimte",
        "SaleOrRent": "",
        "PriceInfo": "#HuurprijsPerJaar# &euro; 212.260, #HuurprijsPerMaand# &euro; 17.688",
        "MetrageInfo": "2.361 m&sup2;",
        "DetailLinkUrl": "2e8b18cb-8a0c-40c9-ab36-702a6a44ea36/Amsterdam/Snijdersbergweg/95",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 200173,
        "UniqueId": "f437bcf6-16f6-4f55-8459-5cfc77e7bfb8",
        "AvailabilityCustom": "",
        "ObjectName": "Noma House",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Gustav Mahlerlaan",
        "Number": null,
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1082 LS",
        "Longitude": 4.868188,
        "Latitude": 52.33695,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/f4/37/bc/f6/f437bcf6-16f6-4f55-8459-5cfc77e7bfb8/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 13694,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": null,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Niels Hanssen",
            "ContactEmailAddress": "niels.hanssen@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Gustav Mahlerlaan",
        "BuildingAddressInfo": "Noma House, Gustav Mahlerlaan",
        "FullAddressInfo": "Noma House, Gustav Mahlerlaan, 1082 LS, Amsterdam",
        "InsertedDateTime": "2015-10-21T15:21:13",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "13.694 m&sup2;",
        "DetailLinkUrl": "f437bcf6-16f6-4f55-8459-5cfc77e7bfb8/Amsterdam/Gustav-Mahlerlaan/onbekend",
        "Availability": ""
    },
    {
        "ObjectId": 199163,
        "UniqueId": "a56d3dc8-6e2a-4ec6-8bb1-206d26bb6de3",
        "AvailabilityCustom": "",
        "ObjectName": "Het Koninklijk Paar",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Anderlechtlaan",
        "Number": "175",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1066 HM",
        "Longitude": 4.812019,
        "Latitude": 52.34351,
        "ObjectTypeId": null,
        "PriceAverage": 175,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/a5/6d/3d/c8/a56d3dc8-6e2a-4ec6-8bb1-206d26bb6de3/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 2940,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Sander van den Engel",
            "ContactEmailAddress": "sander.vandenengel@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Anderlechtlaan  175",
        "BuildingAddressInfo": "Het Koninklijk Paar, Anderlechtlaan  175",
        "FullAddressInfo": "Het Koninklijk Paar, Anderlechtlaan  175, 1066 HM, Amsterdam",
        "InsertedDateTime": "2015-09-10T13:53:26",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 175 m<sup>2<\/sup>/jr",
        "MetrageInfo": "2.940 m&sup2;",
        "DetailLinkUrl": "a56d3dc8-6e2a-4ec6-8bb1-206d26bb6de3/Amsterdam/Anderlechtlaan/175",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 196625,
        "UniqueId": "f9a79b8c-5c18-42d4-bd6d-8dcf046dfebd",
        "AvailabilityCustom": "",
        "ObjectName": "Willemshuis",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Stadhouderskade",
        "Number": "55",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1072 AB",
        "Longitude": 4.888333,
        "Latitude": 52.358738,
        "ObjectTypeId": null,
        "PriceAverage": 245,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/f9/a7/9b/8c/f9a79b8c-5c18-42d4-bd6d-8dcf046dfebd/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 842,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Maarten van Dooren",
            "ContactEmailAddress": "maarten.vandooren@cbre.com",
            "PersonId": 6164,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": "/media/objects/f9/a7/9b/8c/f9a79b8c-5c18-42d4-bd6d-8dcf046dfebd/docs/Willemshuis, Stadhouderskade 55.pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Stadhouderskade  55",
        "BuildingAddressInfo": "Willemshuis, Stadhouderskade  55",
        "FullAddressInfo": "Willemshuis, Stadhouderskade  55, 1072 AB, Amsterdam",
        "InsertedDateTime": "2015-05-12T09:11:38",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 245 m<sup>2<\/sup>/jr",
        "MetrageInfo": "842 m&sup2;",
        "DetailLinkUrl": "f9a79b8c-5c18-42d4-bd6d-8dcf046dfebd/Amsterdam/Stadhouderskade/55",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 195459,
        "UniqueId": "924db912-d5b8-46dc-aa4a-50df53aa0966",
        "AvailabilityCustom": "01-04-2016",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Beethovenstraat",
        "Number": "500",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1082 PR",
        "Longitude": 4.8775883,
        "Latitude": 52.33579,
        "ObjectTypeId": null,
        "PriceAverage": 345,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/92/4d/b9/12/924db912-d5b8-46dc-aa4a-50df53aa0966/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 2018,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 3,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Niels Hanssen",
            "ContactEmailAddress": "niels.hanssen@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Beethovenstraat  500",
        "BuildingAddressInfo": "Beethovenstraat  500",
        "FullAddressInfo": "Beethovenstraat  500, 1082 PR, Amsterdam",
        "InsertedDateTime": "2015-03-24T17:30:57",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 345 m<sup>2<\/sup>/jr",
        "MetrageInfo": "2.018 m&sup2;",
        "DetailLinkUrl": "924db912-d5b8-46dc-aa4a-50df53aa0966/Amsterdam/Beethovenstraat/500",
        "Availability": "01-04-2016"
    },
    {
        "ObjectId": 194164,
        "UniqueId": "f4a74af7-87c1-4937-8373-c6fa51a64514",
        "AvailabilityCustom": "",
        "ObjectName": "Tricity",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Hullenbergweg",
        "Number": "81",
        "NumberRangeTo": "135",
        "NumberSuffix": null,
        "Postcode": "1101 CL",
        "Longitude": 4.949296,
        "Latitude": 52.30392,
        "ObjectTypeId": null,
        "PriceAverage": 145,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/f4/a7/4a/f7/f4a74af7-87c1-4937-8373-c6fa51a64514/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 16056,
        "MetrageStart": 235,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Merel van Oudvorst",
            "ContactEmailAddress": "merel.vanoudvorst@cbre.com",
            "PersonId": null,
            "Phonenumber": "20-626 26 91",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": "/media/objects/f4/a7/4a/f7/f4a74af7-87c1-4937-8373-c6fa51a64514/docs/PI-NED-Tricity-Hullenbergweg-81-135-Amsterdam-Zuidoost.pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Hullenbergweg  81-135",
        "BuildingAddressInfo": "Tricity, Hullenbergweg  81-135",
        "FullAddressInfo": "Tricity, Hullenbergweg  81-135, 1101 CL, Amsterdam",
        "InsertedDateTime": "2015-02-05T12:03:40",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 145 m<sup>2<\/sup>/jr",
        "MetrageInfo": "16.056 m&sup2; #Vanaf# 235m&sup2;",
        "DetailLinkUrl": "f4a74af7-87c1-4937-8373-c6fa51a64514/Amsterdam/Hullenbergweg/81-135",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 192279,
        "UniqueId": "b6ebb9cb-a91f-4117-95fa-bafe5eaac9c3",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Amstelveenseweg",
        "Number": "760",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1081 JK",
        "Longitude": 4.856996,
        "Latitude": 52.331352,
        "ObjectTypeId": null,
        "PriceAverage": 245,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/b6/eb/b9/cb/b6ebb9cb-a91f-4117-95fa-bafe5eaac9c3/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 2166,
        "MetrageStart": 416,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "2775CBBF720443F2984E02149EE32E4A",
            "Name": "P van den Bosch bedrijfsmakelaars (Amsterdam)",
            "Address": "Amsterdamsestraatweg 41A",
            "City": "Baarn",
            "Postcode": "3744 MA",
            "ContactPersonName": "de heer M. Zwiers",
            "ContactEmailAddress": "info@pvdbosch.nl",
            "PersonId": 2619,
            "Phonenumber": "020-3052929",
            "Logo": "P van den Bosch.JPG",
            "CanonicalName": "P-van-den-Bosch-bedrijfsmakelaars-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Amstelveenseweg  760",
        "BuildingAddressInfo": "Amstelveenseweg  760",
        "FullAddressInfo": "Amstelveenseweg  760, 1081 JK, Amsterdam",
        "InsertedDateTime": "2014-12-24T11:51:35",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 245 m<sup>2<\/sup>/jr",
        "MetrageInfo": "2.166 m&sup2; #Vanaf# 416m&sup2;",
        "DetailLinkUrl": "b6ebb9cb-a91f-4117-95fa-bafe5eaac9c3/Amsterdam/Amstelveenseweg/760",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 190795,
        "UniqueId": "F0B3D62C-A01F-4814-9946-2E0EE88D3DE2",
        "AvailabilityCustom": "",
        "ObjectName": "Singelstaete",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Singel",
        "Number": "250",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1016 AB",
        "Longitude": 4.8882732,
        "Latitude": 52.372955,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/F0/B3/D6/2C/F0B3D62C-A01F-4814-9946-2E0EE88D3DE2/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 2585,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Maarten van Dooren en Laura Hovestad",
            "ContactEmailAddress": "maarten.vandooren@cbre.com",
            "PersonId": 6164,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Singel  250",
        "BuildingAddressInfo": "Singelstaete, Singel  250",
        "FullAddressInfo": "Singelstaete, Singel  250, 1016 AB, Amsterdam",
        "InsertedDateTime": "2014-11-06T11:48:08",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "2.585 m&sup2;",
        "DetailLinkUrl": "F0B3D62C-A01F-4814-9946-2E0EE88D3DE2/Amsterdam/Singel/250",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 180118,
        "UniqueId": "B647AEBE-0576-45ED-A7BF-C9436185B32E",
        "AvailabilityCustom": "",
        "ObjectName": "Bright Offices, gebouw B",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "La Guardiaweg",
        "Number": "36",
        "NumberRangeTo": "68",
        "NumberSuffix": null,
        "Postcode": "1043 DJ",
        "Longitude": 4.839309,
        "Latitude": 52.391243,
        "ObjectTypeId": null,
        "PriceAverage": 175,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/B6/47/AE/BE/B647AEBE-0576-45ED-A7BF-C9436185B32E/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 5909,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Sander van den Engel",
            "ContactEmailAddress": "sander.vandenengel@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "La Guardiaweg  36-68",
        "BuildingAddressInfo": "Bright Offices, gebouw B, La Guardiaweg  36-68",
        "FullAddressInfo": "Bright Offices, gebouw B, La Guardiaweg  36-68, 1043 DJ, Amsterdam",
        "InsertedDateTime": "2014-03-21T16:36:47",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 175 m<sup>2<\/sup>/jr",
        "MetrageInfo": "5.909 m&sup2;",
        "DetailLinkUrl": "B647AEBE-0576-45ED-A7BF-C9436185B32E/Amsterdam/La-Guardiaweg/36-68",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 180103,
        "UniqueId": "DDF28012-AFAC-4956-8A13-CDEBD5A3B23F",
        "AvailabilityCustom": "",
        "ObjectName": "Bright Offices gebouw A",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "La Guardiaweg",
        "Number": "36",
        "NumberRangeTo": "68",
        "NumberSuffix": null,
        "Postcode": "1043 DJ",
        "Longitude": 4.839309,
        "Latitude": 52.391243,
        "ObjectTypeId": null,
        "PriceAverage": 175,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/DD/F2/80/12/DDF28012-AFAC-4956-8A13-CDEBD5A3B23F/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 1394,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Sander van den Engel",
            "ContactEmailAddress": "sander.vandenengel@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "La Guardiaweg  36-68",
        "BuildingAddressInfo": "Bright Offices gebouw A, La Guardiaweg  36-68",
        "FullAddressInfo": "Bright Offices gebouw A, La Guardiaweg  36-68, 1043 DJ, Amsterdam",
        "InsertedDateTime": "2014-03-21T14:55:44",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 175 m<sup>2<\/sup>/jr",
        "MetrageInfo": "1.394 m&sup2;",
        "DetailLinkUrl": "DDF28012-AFAC-4956-8A13-CDEBD5A3B23F/Amsterdam/La-Guardiaweg/36-68",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 179905,
        "UniqueId": "44C58CB3-9E1C-47EB-9A6C-A52696B71CE7",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 2,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Scharenburg",
        "Number": "3",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1046 BA",
        "Longitude": 4.7845125,
        "Latitude": 52.3959,
        "ObjectTypeId": null,
        "PriceAverage": 52,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/44/C5/8C/B3/44C58CB3-9E1C-47EB-9A6C-A52696B71CE7/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 15200,
        "MetrageStart": 7500,
        "SalesHeaderLine": "HOOGWAARDIG LOGISTIEK GEBOUW MET EIGEN AFSLAG AAN RIJKSWEG A5 !",
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "AB16EE3FEEEA4205B59E961545AB0406",
            "Name": "INDUSTRIAL real estate partners (Schiphol)",
            "Address": "Stationsplein-ZW 989",
            "City": "Schiphol",
            "Postcode": "1117 CE",
            "ContactPersonName": "M. Hoekstra",
            "ContactEmailAddress": "industrial@industrial.nl",
            "PersonId": 15114,
            "Phonenumber": "088-9899898",
            "Logo": "Industrial_klein.png",
            "CanonicalName": "INDUSTRIAL-real-estate-partners-(Schiphol)"
        },
        "BrochureUrl": "/media/objects/44/C5/8C/B3/44C58CB3-9E1C-47EB-9A6C-A52696B71CE7/docs/PI-Scharenburg-3-Amsterdam.pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Scharenburg  3",
        "BuildingAddressInfo": "Scharenburg  3",
        "FullAddressInfo": "Scharenburg  3, 1046 BA, Amsterdam",
        "InsertedDateTime": "2014-03-19T13:33:58",
        "PrimaryUsage": "Bedrijfsruimte",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 52 m<sup>2<\/sup>/jr",
        "MetrageInfo": "15.200 m&sup2; #Vanaf# 7.500m&sup2;",
        "DetailLinkUrl": "44C58CB3-9E1C-47EB-9A6C-A52696B71CE7/Amsterdam/Scharenburg/3",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 175759,
        "UniqueId": "032242A1-F2B0-4F77-BF67-2B047B7BBF82",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Spaklerweg",
        "Number": "53",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1114 AE",
        "Longitude": 4.926693,
        "Latitude": 52.33004,
        "ObjectTypeId": null,
        "PriceAverage": 135,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/03/22/42/A1/032242A1-F2B0-4F77-BF67-2B047B7BBF82/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 3277,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Merel van Oudvorst",
            "ContactEmailAddress": "merel.vanoudvorst@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Spaklerweg  53",
        "BuildingAddressInfo": "Spaklerweg  53",
        "FullAddressInfo": "Spaklerweg  53, 1114 AE, Amsterdam",
        "InsertedDateTime": "2013-12-30T11:06:20",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 135 m<sup>2<\/sup>/jr",
        "MetrageInfo": "3.277 m&sup2;",
        "DetailLinkUrl": "032242A1-F2B0-4F77-BF67-2B047B7BBF82/Amsterdam/Spaklerweg/53",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 175758,
        "UniqueId": "1D0D6095-3418-45F1-BF5A-768363C67AF4",
        "AvailabilityCustom": "",
        "ObjectName": "Emerald House",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Jozef IsraÃ«lskade",
        "Number": "46",
        "NumberRangeTo": "48",
        "NumberSuffix": null,
        "Postcode": "1072 SB",
        "Longitude": 4.891589,
        "Latitude": 52.34841,
        "ObjectTypeId": null,
        "PriceAverage": 250,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/1D/0D/60/95/1D0D6095-3418-45F1-BF5A-768363C67AF4/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 312,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Maarten van Dooren en Laura Hovestad",
            "ContactEmailAddress": "maarten.vandooren@cbre.com / laura.hovestad@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Jozef IsraÃ«lskade  46-48",
        "BuildingAddressInfo": "Emerald House, Jozef IsraÃ«lskade  46-48",
        "FullAddressInfo": "Emerald House, Jozef IsraÃ«lskade  46-48, 1072 SB, Amsterdam",
        "InsertedDateTime": "2013-12-30T10:37:01",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 250 m<sup>2<\/sup>/jr",
        "MetrageInfo": "312 m&sup2;",
        "DetailLinkUrl": "1D0D6095-3418-45F1-BF5A-768363C67AF4/Amsterdam/Jozef-Isralskade/46-48",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 175383,
        "UniqueId": "DFE54CF2-2A71-4502-97F4-C513BCB2688A",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Arlandaweg",
        "Number": "100",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1043 HP",
        "Longitude": 4.841404,
        "Latitude": 52.385788,
        "ObjectTypeId": null,
        "PriceAverage": 155,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/DF/E5/4C/F2/DFE54CF2-2A71-4502-97F4-C513BCB2688A/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 5385,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "198D75A9A31A4300BEDFC028DF0C38A7",
            "Name": "Savills (Amsterdam)",
            "Address": "Postbus 75849",
            "City": "Amsterdam",
            "Postcode": "1070 AV",
            "ContactPersonName": "Olivier Schel",
            "ContactEmailAddress": "o.schel@savills.nl",
            "PersonId": null,
            "Phonenumber": "020-3012029",
            "Logo": "savills_logo.gif",
            "CanonicalName": "Savills-(Amsterdam)"
        },
        "BrochureUrl": "/media/objects/DF/E5/4C/F2/DFE54CF2-2A71-4502-97F4-C513BCB2688A/docs/Projectinformatie-Arlandaweg-100-Amsterdam-(ENG).pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Arlandaweg  100",
        "BuildingAddressInfo": "Arlandaweg  100",
        "FullAddressInfo": "Arlandaweg  100, 1043 HP, Amsterdam",
        "InsertedDateTime": "2013-12-17T18:04:42",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 155 m<sup>2<\/sup>/jr",
        "MetrageInfo": "5.385 m&sup2;",
        "DetailLinkUrl": "DFE54CF2-2A71-4502-97F4-C513BCB2688A/Amsterdam/Arlandaweg/100",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 169179,
        "UniqueId": "DAFFA6A1-12C0-4F27-B6D9-F16CB0D801EF",
        "AvailabilityCustom": "",
        "ObjectName": "Cuserpark",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "De Cuserstraat",
        "Number": "83",
        "NumberRangeTo": "91",
        "NumberSuffix": null,
        "Postcode": "1081 CN",
        "Longitude": 4.859132,
        "Latitude": 52.323555,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/DA/FF/A6/A1/DAFFA6A1-12C0-4F27-B6D9-F16CB0D801EF/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 759,
        "MetrageStart": 392,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Niels Hanssen / Sander van den Engel",
            "ContactEmailAddress": "niels.hanssen@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "De Cuserstraat  83-91",
        "BuildingAddressInfo": "Cuserpark, De Cuserstraat  83-91",
        "FullAddressInfo": "Cuserpark, De Cuserstraat  83-91, 1081 CN, Amsterdam",
        "InsertedDateTime": "2013-08-20T10:13:57",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "759 m&sup2; #Vanaf# 392m&sup2;",
        "DetailLinkUrl": "DAFFA6A1-12C0-4F27-B6D9-F16CB0D801EF/Amsterdam/De-Cuserstraat/83-91",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 155182,
        "UniqueId": "0954BC53-066F-47D9-A8FD-0FF0E5910E8E",
        "AvailabilityCustom": "",
        "ObjectName": "Business Court Amsterdam",
        "ObjectUsageId": 2,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Maroastraat",
        "Number": "2",
        "NumberRangeTo": null,
        "NumberSuffix": " -26",
        "Postcode": "1060 LG",
        "Longitude": 4.76845,
        "Latitude": 52.35569,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/09/54/BC/53/0954BC53-066F-47D9-A8FD-0FF0E5910E8E/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 6520,
        "MetrageStart": 955,
        "SalesHeaderLine": "Maroastraat 2-26, Amsterdam",
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "F7E9C93DDD2549CFAFFB65B485DC259A",
            "Name": "DTZ Zadelhoff Hoofddorp (Hoofddorp)",
            "Address": "Postbus 2028",
            "City": "Hoofddorp",
            "Postcode": "2130 GE",
            "ContactPersonName": "Agency - Industrial",
            "ContactEmailAddress": "hoofddorp@dtz.nl",
            "PersonId": 18275,
            "Phonenumber": "023-5685685",
            "Logo": "DTZ_Zadelhoff.png",
            "CanonicalName": "DTZ-Zadelhoff-Hoofddorp-(Hoofddorp)"
        },
        "BrochureUrl": "/media/objects/09/54/BC/53/0954BC53-066F-47D9-A8FD-0FF0E5910E8E/docs/Brochure.pdf",
        "VideoUrl": "https://vimeo.com/120348110",
        "TourUrl": null,
        "Address": "Maroastraat  2 -26",
        "BuildingAddressInfo": "Business Court Amsterdam, Maroastraat  2 -26",
        "FullAddressInfo": "Business Court Amsterdam, Maroastraat  2 -26, 1060 LG, Amsterdam",
        "InsertedDateTime": "2012-11-30T10:23:26",
        "PrimaryUsage": "Bedrijfsruimte",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "6.520 m&sup2; #Vanaf# 955m&sup2;",
        "DetailLinkUrl": "0954BC53-066F-47D9-A8FD-0FF0E5910E8E/Amsterdam/Maroastraat/2-26",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 148907,
        "UniqueId": "E9326B15-2780-40DE-B16D-70D05703A192",
        "AvailabilityCustom": "",
        "ObjectName": "Cristofori",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Prinsengracht",
        "Number": "581",
        "NumberRangeTo": "583",
        "NumberSuffix": null,
        "Postcode": "1016 HT",
        "Longitude": 4.8828483,
        "Latitude": 52.368023,
        "ObjectTypeId": null,
        "PriceAverage": null,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/E9/32/6B/15/E9326B15-2780-40DE-B16D-70D05703A192/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 366,
        "MetrageStart": 100,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Maarten van Dooren en Laura Hovestad",
            "ContactEmailAddress": "maarten.vandooren@cbre.com",
            "PersonId": 6164,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Prinsengracht  581-583",
        "BuildingAddressInfo": "Cristofori, Prinsengracht  581-583",
        "FullAddressInfo": "Cristofori, Prinsengracht  581-583, 1016 HT, Amsterdam",
        "InsertedDateTime": "2012-08-15T15:49:56",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "",
        "MetrageInfo": "366 m&sup2; #Vanaf# 100m&sup2;",
        "DetailLinkUrl": "E9326B15-2780-40DE-B16D-70D05703A192/Amsterdam/Prinsengracht/581-583",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 141443,
        "UniqueId": "7B4A5B6E-BAF0-4E62-A182-A5EA19FF80D2",
        "AvailabilityCustom": "",
        "ObjectName": "De Entree II",
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "De entree",
        "Number": "230",
        "NumberRangeTo": "260",
        "NumberSuffix": "",
        "Postcode": "1101 EE",
        "Longitude": 4.9409485,
        "Latitude": 52.30999,
        "ObjectTypeId": null,
        "PriceAverage": 185,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/7B/4A/5B/6E/7B4A5B6E-BAF0-4E62-A182-A5EA19FF80D2/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 2523,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "7F54CF7DAD2C41CDA21B9330A379A02B",
            "Name": "Colliers International Netherlands (Amsterdam)",
            "Address": "Buitenveldertselaan 5",
            "City": "Amsterdam",
            "Postcode": "1082 VA",
            "ContactPersonName": "Nick de Sonnaville",
            "ContactEmailAddress": "amsterdam.agency@colliers.com",
            "PersonId": null,
            "Phonenumber": "020-5405520",
            "Logo": "Colliers_Logo.jpg",
            "CanonicalName": "Colliers-International-Netherlands-(Amsterdam)"
        },
        "BrochureUrl": "/media/objects/7B/4A/5B/6E/7B4A5B6E-BAF0-4E62-A182-A5EA19FF80D2/docs/De-Entree-II.pdf",
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "De entree  230-260",
        "BuildingAddressInfo": "De Entree II, De entree  230-260",
        "FullAddressInfo": "De Entree II, De entree  230-260, 1101 EE, Amsterdam",
        "InsertedDateTime": "2012-03-30T11:07:24",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 185 m<sup>2<\/sup>/jr",
        "MetrageInfo": "2.523 m&sup2;",
        "DetailLinkUrl": "7B4A5B6E-BAF0-4E62-A182-A5EA19FF80D2/Amsterdam/De-entree/230-260",
        "Availability": "Per direct"
    },
    {
        "ObjectId": 138912,
        "UniqueId": "3E9ED365-3615-4F84-8359-DE6A1B3BE1DD",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 1,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Weteringschans",
        "Number": "109",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1017 SB",
        "Longitude": 4.8877163,
        "Latitude": 52.360836,
        "ObjectTypeId": null,
        "PriceAverage": 230,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/3E/9E/D3/65/3E9ED365-3615-4F84-8359-DE6A1B3BE1DD/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 772,
        "MetrageStart": null,
        "SalesHeaderLine": null,
        "AvailabilityId": 2,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer/mevrouw",
            "GUID": "4E1F65CB38D54E92A6458D6385B7FB05",
            "Name": "CBRE (Amsterdam)",
            "Address": "Postbus 7971",
            "City": "Amsterdam",
            "Postcode": "1008 AD",
            "ContactPersonName": "Maarten van Dooren en Laura Hovestad",
            "ContactEmailAddress": "maarten.vandooren@cbre.com / laura.hovestad@cbre.com",
            "PersonId": null,
            "Phonenumber": "020-6262691",
            "Logo": "CBRE.png",
            "CanonicalName": "CBRE-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Weteringschans  109",
        "BuildingAddressInfo": "Weteringschans  109",
        "FullAddressInfo": "Weteringschans  109, 1017 SB, Amsterdam",
        "InsertedDateTime": "2012-02-17T11:25:37",
        "PrimaryUsage": "Kantoor",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 230 m<sup>2<\/sup>/jr",
        "MetrageInfo": "772 m&sup2;",
        "DetailLinkUrl": "3E9ED365-3615-4F84-8359-DE6A1B3BE1DD/Amsterdam/Weteringschans/109",
        "Availability": "In overleg"
    },
    {
        "ObjectId": 107140,
        "UniqueId": "AC78F9B7-082F-45C8-9B70-DB6D2663D410",
        "AvailabilityCustom": "",
        "ObjectName": null,
        "ObjectUsageId": 2,
        "CountryId": null,
        "City": "Amsterdam",
        "Street": "Westhavenweg",
        "Number": "53",
        "NumberRangeTo": null,
        "NumberSuffix": null,
        "Postcode": "1042 AL",
        "Longitude": 4.8300133,
        "Latitude": 52.40737,
        "ObjectTypeId": null,
        "PriceAverage": 33,
        "PriceNOTK": false,
        "ImageURL": "/media/objects/AC/78/F9/B7/AC78F9B7-082F-45C8-9B70-DB6D2663D410/thumb/1.jpg",
        "Price": null,
        "PricePerYear": null,
        "Metrage": 5814,
        "MetrageStart": null,
        "SalesHeaderLine": "Moderne hoge bedrijfsloods.",
        "AvailabilityId": 1,
        "ActivateDate": null,
        "SalesPriceType": null,
        "Broker": {
            "Salutation": "mijnheer",
            "GUID": "64A048A966B146BA9CE66430D3D66193",
            "Name": "Blaauwhof Makelaars (Amsterdam)",
            "Address": "Dukdalfweg 60",
            "City": "Amsterdam",
            "Postcode": "1041 BE",
            "ContactPersonName": "Jeroen D. Faber RT",
            "ContactEmailAddress": "jdfaber@blaauwhof.nl",
            "PersonId": 2041,
            "Phonenumber": "020-4203200",
            "Logo": "blaauwhof.jpg",
            "CanonicalName": "Blaauwhof-Makelaars-(Amsterdam)"
        },
        "BrochureUrl": null,
        "VideoUrl": null,
        "TourUrl": null,
        "Address": "Westhavenweg  53",
        "BuildingAddressInfo": "Westhavenweg  53",
        "FullAddressInfo": "Westhavenweg  53, 1042 AL, Amsterdam",
        "InsertedDateTime": "2010-12-16T14:19:43",
        "PrimaryUsage": "Bedrijfsruimte",
        "SaleOrRent": "",
        "PriceInfo": "#Huurprijs# &euro; 33 m<sup>2<\/sup>/jr",
        "MetrageInfo": "5.814 m&sup2;",
        "DetailLinkUrl": "AC78F9B7-082F-45C8-9B70-DB6D2663D410/Amsterdam/Westhavenweg/53",
        "Availability": "Per direct"
    }
];